{{- if .Values.persistence.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ ternary "true" "false" .Values.persistence.storageClass.isDefaultClass | quote }}
provisioner: {{ .Values.persistence.storageClass.provisioner | quote }}
reclaimPolicy: Delete
volumeBindingMode: {{ .Values.persistence.storageClass.volumeBindingMode | quote }}
allowVolumeExpansion: {{ .Values.persistence.storageClass.allowVolumeExpansion }}
{{- if .Values.persistence.storageClass.parameters }}
parameters:
{{- range $k, $v := .Values.persistence.storageClass.parameters }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvc.name }}
spec:
  accessModes:
{{- range .Values.persistence.pvc.accessModes }}
  - {{ . }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
  storageClassName: {{ .Values.persistence.pvc.storageClass }}
{{- end }}
