apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller-dev
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.0
    helm:
      values: |
        clusterName: weather-app-eks
        region: us-east-1
        vpcId: vpc-02ee336af566d61f6
        serviceAccount:
          create: false
          name: aws-load-balancer-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
