weather:
  replicas: 4
  image:
    repository: omerlevyk/weather_app_private
    tag: v1.0.1-20260218-1
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 5000
    nodePort: 32300
  bgColorConfigMap: bg-color-blue
  historyMountPath: /app/history

solitaire:
  replicas: 4
  image:
    repository: chimenesjr/solitaire
    tag: nginx
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 32400

configMaps:
  blue:
    name: bg-color-blue
    bgColor: blue
  green:
    name: bg-color-green
    bgColor: green

persistence:
  enabled: true
  storageClass:
    name: weather-efs-sc-v1
    isDefaultClass: false
    provisioner: efs.csi.aws.com
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-02f7530e598c97d62
      directoryPerms: "700"
  pvc:
    name: weather-history-pvc-efs-v1
    storageClass: weather-efs-sc-v1
    size: 5Gi
    accessModes:
      - ReadWriteMany

ingress:
  enabled: true
  className: alb
  loadBalancerName: apps-ingress
  weatherHost: weather.omerlevy03.com
  solitaireHost: solitaire.omerlevy03.com
  certificateArn: arn:aws:acm:us-east-1:960828421635:certificate/354e07ad-76e2-4921-a459-85fe48702d1f
